apiVersion: v1
kind: Namespace
metadata: 
  name: react
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  namespace: react
spec:
  selector:
    app: nginx
  ports:
    - name: react-port
      port: 8081
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  namespace: react
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: react
        image: ayiangio/react-zalora-kw:tagVersion
        ports:
        - containerPort: 80
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  react-maping
  namespace: react
spec:
  prefix: /
  service: http://react-service:8081

---
apiVersion: getambassador.io/v2
kind: Host
metadata:
  name: react-host
  namespace: react
spec:
  hostname: react.ayiangio.xyz
  acmeProvider:
    email: moh41.angio@gmail.com