
version: '3'
services: 
  nginx:
    image: nginx:1.16.1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/usr/share/nginx/html
      - ./webserver/nginx.conf:/etc/nginx/conf.d/default.conf      
    command: "nginx -g 'daemon off ;'"
